name: Test

on:
  push:
    branches:
    - '*'

jobs:
  ci-current:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        include:
          - php-version: "7.4"
            wordpress-version: "5.6.10"
            woocommerce-version: "5.6.2"
          - php-version: "8.0"
            wordpress-version: "5.9.5"
            woocommerce-version: "6.9.4"
          - php-version: "8.1"
            wordpress-version: "6.1"
            woocommerce-version: "7.4.1"
          - php-version: "8.2"
            wordpress-version: "6.2"
            woocommerce-version: "7.8.2"
          - php-version: "8.2"
            wordpress-version: "6.3"
            woocommerce-version: "7.9.0"
          - php-version: "8.2"
            wordpress-version: "6.3"
            woocommerce-version: "8.0.3"
          - php-version: "8.2"
            wordpress-version: "6.3"
            woocommerce-version: "8.1.0"
          - php-version: "8.2"
            wordpress-version: "6.4"
            woocommerce-version: "8.4.0"
          - php-version: "8.2"
            wordpress-version: "6.5"
            woocommerce-version: "8.6.1"
          - php-version: "8.3"
            wordpress-version: "6.5"
            woocommerce-version: "8.9.1"

    name: woo v${{ matrix.woocommerce-version }}, wp v${{ matrix.wordpress-version }} @ php v${{ matrix.php-version }}

    env:
      WORDPRESS_DIR: /opt/wordpress
      PLUGIN_DIR: /opt/wordpress/wp-content/plugins/wc-easycredit
      WORDPRESS_DB_HOST: 127.0.0.1
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: true
      WP_CLI_ALLOW_ROOT: true
 
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install wp-env
        shell: bash
        run: npm -g i @wordpress/env
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          #extensions: mbstring, curl, dom, fileinfo, gd, iconv, intl, json, xml, mbstring, pdo, phar, zip, sodium
          extensions: json, curl, dom, mbstring, intl, xml, zip, apcu, opcache
          tools: composer:2.1.5
          coverage: xdebug
          ini-values: error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT"
      - name: Debug
        run: |
          php -v
          php -i
          env
          node -v
      - name: Install Wordpress & wooCommerce
        run: | 
          node -e 'console.log(JSON.stringify({"core": "WordPress/WordPress#${{ matrix.wordpress-version }}", "phpVersion": "${{ matrix.php-version }}", "lifecycleScripts":{}}, null, 2));' > .wp-env.override.json
          wp-env start

          composer require \
            php-stubs/wordpress-stubs:v${{ matrix.wordpress-version }} \
            php-stubs/woocommerce-stubs:v${{ matrix.woocommerce-version }} 

          composer install -n

          # run setup script standalone, was not reliably executed as lifecycle script
          VERSION=${{ matrix.woocommerce-version }} node ./scripts/setup-woocommerce.js

          echo '{"enabled":"yes","display_settings":"","title":"","instructions":"","api_details":"","api_key":"${{ secrets.EASYCREDITAPIKEY }}","api_token":"${{ secrets.EASYCREDITAPIPASSWORD }}","api_signature":"${{ secrets.EASYCREDITAPISIGNATURE }}","api_verify_credentials":"","debug":"yes","marketing_intro":"","marketing_components_express_checkout":"","express_checkout_detail_enabled":"yes","express_checkout_cart_enabled":"yes","marketing_components_widget":"","widget_enabled":"yes","widget_selector":".product .summary .price","cart_widget_enabled":"yes","cart_widget_selector":".wc-proceed-to-checkout","marketing_components_modal":"","modal_enabled":"no","modal_delay":"10","modal_snooze_for":"10","modal_src":"","marketing_components_card":"","card_enabled":"no","card_search_enabled":"no","card_position":"1","card_src":"","marketing_components_flashbox":"","flashbox_enabled":"no","flashbox_src":"","marketing_components_bar":"","bar_enabled":"no","transactions":"","mark_shipped":"no","mark_shipped_status":"wc-completed","mark_refunded":"no","mark_refunded_status":"wc-refunded","clickandcollect_intro":"","marketing_components_clickandcollect":"","clickandcollect_shipping_method":""}' | wp-env run cli wp option set woocommerce_easycredit_settings --format=json
      - name: Static Analyze
        if: false
        run: | 
          cd $PLUGIN_DIR
          php vendor/bin/phpstan analyze .
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
#      - name: Store Playwright's Version
#        run: |
#          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
#          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
#          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
#      - name: Cache Playwright Browsers for Playwright's Version
#        id: cache-playwright-browsers
#        uses: actions/cache@v4
#        with:
#          path: ~/.cache/ms-playwright
#          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
      - name: Setup Playwright
#        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps chromium
      - name: Playwright E2E Tests
        run: |
          cd $GITHUB_WORKSPACE

          VERSION=${{ matrix.woocommerce-version }} BASE_URL=http://localhost:8888 yarn playwright test -c tests/
      - name: Save Logs for Debugging
        if: always()
        run: |
          mkdir -p test-results/${{ matrix.woocommerce-version }}
          cp -r $WORDPRESS_DIR/wp-content/debug.log $WORDPRESS_DIR/wp-content/uploads/wc-logs/*.log test-results/${{ matrix.woocommerce-version }}/ 
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: test-results/
          retention-days: 7
